// Generated by course/_build/articles.js
window.EXPLAIN_ARTICLES = [
 {
  "slug": "what-your-ai-product-actually-is",
  "title": "Most of what you call the AI is not the model",
  "dek": "A map of the eight parts around the model, and a five-minute method for drawing it for any product.",
  "tag": "Systems",
  "date": "2026-09-27",
  "minutes": 4
 },
 {
  "slug": "confident-and-wrong",
  "title": "Why a confident answer is not a verified one",
  "dek": "How fluent text goes wrong, what confidence actually measures, and which outputs a product must check in code.",
  "tag": "Reliability",
  "date": "2026-09-20",
  "minutes": 4
 },
 {
  "slug": "workflow-or-agent",
  "title": "Autonomy is a cost, so decide where you spend it",
  "dek": "How to choose between a fixed workflow, one model-chosen branch and a full agent loop, and where approval belongs.",
  "tag": "Agents",
  "date": "2026-09-13",
  "minutes": 4
 }
];
