// Generated by course/_build/build.js
window.EXPLAIN_CHEATSHEETS = {
 "m00": {
  "big_idea": "Most of what users call “the AI” is the system you build around the model.",
  "ask": [
   "Which ring is this really: hand-written rules, classic ML or a generative model?",
   "What exactly is sent to the model on each call, and who decides that?",
   "Where do facts the model can’t know come from: private data, recent events?",
   "Which actions can it take, and who or what approves them before they run?",
   "How will we know it got worse after a model, prompt or data change?"
  ],
  "rules": [
   "Name the box before you fix anything: model, context, knowledge, tools or another.",
   "Rule out context, knowledge and tools before you blame the model.",
   "Use a plain rule instead of a model when a fixed rule does the job reliably.",
   "Judge quality on a set of test cases you can rerun, not on one good demo."
  ],
  "red_flags": [
   "“The AI decided” and nobody can say which part made the call",
   "Nobody can list what goes into the model’s context on a request",
   "The model can take actions with no permission check or approval step",
   "A launch plan with no way to measure quality after changes"
  ],
  "terms": [
   {
    "term": "Model",
    "def": "Trained weights behind an endpoint: text in, predicted text out."
   },
   {
    "term": "Inference",
    "def": "Running the trained model on a request. Its weights don’t change."
   },
   {
    "term": "Orchestration",
    "def": "The logic that decides which steps, model calls and tools run, and in what order."
   },
   {
    "term": "Guardrails",
    "def": "Checks and limits around the model: filters, permissions, approvals."
   },
   {
    "term": "Evaluation",
    "def": "Repeatable tests that show whether the system is good enough, and stays so."
   }
  ],
  "tool": {
   "title": "System map in five minutes",
   "kind": "checklist",
   "items": [
    "Pick one real user request and trace it from the interface to the answer, step by step.",
    "Mark the model call. Every other step belongs to the system.",
    "Sort each step into the eight boxes; one step can touch two boxes.",
    "For each empty box, ask: missing by design, or missing by accident?",
    "Note what each box adds per request in cost and delay.",
    "Circle the box most likely to fail first, and name who owns it."
   ]
  }
 },
 "m01": {
  "big_idea": "Every answer is shaped by what’s in the context: choose it, measure it, pay for it.",
  "ask": [
   "What is in the context on a typical call, and how many tokens does each part take?",
   "Which parts of that context does this answer actually need?",
   "Where do the key rule and facts sit: at the start, buried mid-way, or by the question?",
   "What gets trimmed when the window fills, and would anyone notice?",
   "Do any sources in the context contradict each other or include outdated versions?"
  ],
  "rules": [
   "Count tokens with the model’s own tokenizer; don’t estimate from word counts.",
   "Send only what this request needs; cut stale versions and unrelated history.",
   "Keep critical rules in instructions sent every call; restate them near the question.",
   "Estimate tokens per call × calls per day before deciding how much context to send."
  ],
  "red_flags": [
   "“Just put the whole handbook in the prompt, the window is big enough”",
   "Old and current versions of a policy side by side in the same context",
   "Nobody knows the token count or cost of a typical request",
   "Testing only on short chats, never on long conversations"
  ],
  "terms": [
   {
    "term": "Token",
    "def": "A piece of text (word, word part or symbol) that the model reads as one number."
   },
   {
    "term": "Embedding",
    "def": "A long list of numbers representing a token; related meanings sit close together."
   },
   {
    "term": "Attention",
    "def": "How each token weighs earlier tokens to pull in what’s relevant to it."
   },
   {
    "term": "Context window",
    "def": "The hard token limit for everything in one call, the answer included."
   },
   {
    "term": "Dilution",
    "def": "Relevant text used less reliably because unrelated text competes with it."
   }
  ],
  "tool": {
   "title": "Context budget check",
   "kind": "checklist",
   "items": [
    "List every source in the context: instructions, history, documents, tool output, question.",
    "Count tokens per source with the real tokenizer and note the biggest share.",
    "Cut what this request doesn’t need: stale versions, unrelated turns, noisy tool output.",
    "Keep key rules in instructions, label key facts, and put the question near the end.",
    "Check what gets trimmed near the window limit, and leave room for the answer.",
    "Multiply tokens per call by calls per day, and time a long request end to end."
   ]
  }
 },
 "m02": {
  "big_idea": "Weights change only in training. Every other change lives in context, memory or state.",
  "ask": [
   "Does this need new behavior from the model, or just new facts?",
   "How often does this information change, and who must be able to update it?",
   "Should this change apply to one chat, one user or everyone?",
   "Is this fact common, rare, private or newer than the model’s knowledge cutoff?",
   "When the provider ships a new model version, what must we re-test or redo?"
  ],
  "rules": [
   "Keep facts that change in a source of truth fed into context, never in the weights.",
   "Consider fine-tuning for consistent style, format or a narrow task, not to add facts.",
   "Treat the model’s recall of rare, private or recent facts as unreliable.",
   "Treat user feedback as logged data: it changes nothing until someone acts on it."
  ],
  "red_flags": [
   "“Users will correct it and it’ll learn over time”, with no pipeline behind it",
   "A plan to fine-tune on docs so the model “knows” current policies",
   "Answers about recent events with no search tool or retrieval behind them",
   "Nobody can say where a wrong fact came from: weights, prompt or data"
  ],
  "terms": [
   {
    "term": "Parameters",
    "def": "The numbers (weights) set by training. They don’t move while the model is used."
   },
   {
    "term": "Post-training",
    "def": "Further training that turns a text predictor into an assistant with set behaviors."
   },
   {
    "term": "Fine-tuning",
    "def": "Your own training run on your examples: a new model version to host and maintain."
   },
   {
    "term": "Memory",
    "def": "Stored notes or history that the system re-sends as context on later requests."
   },
   {
    "term": "Application state",
    "def": "What your product writes (orders, files, logs); it reaches the model only if sent."
   }
  ],
  "tool": {
   "title": "Where does this change live?",
   "kind": "decision",
   "items": [
    "If it matters for this request only → put it in the context.",
    "If one user needs it across sessions → save it as memory, re-sent as context.",
    "If it’s a fact that changes, like a price or policy → fix the source of truth and retrieve it.",
    "If it records what happened, like an order or feedback → it’s application state.",
    "If you need consistent behavior that prompts can’t get → consider a fine-tune, then evaluate.",
    "If you need newer general knowledge in the weights → a new model version; until then, context."
   ]
  }
 },
 "m03": {
  "big_idea": "Treat every output as a likely guess until something outside the model checks it.",
  "ask": [
   "What does one wrong output cost here, and who pays for it?",
   "Which parts are exact values: numbers, names, dates, IDs or citations?",
   "What catches an error before a user sees it, and does it depend on the model?",
   "Where do we need the same output twice, for tests, audits or caching?",
   "Would more reasoning help, or is the model missing a fact nobody gave it?"
  ],
  "rules": [
   "Get numbers, prices and policy values from source systems; let the model only phrase them.",
   "Store outputs you must reproduce; never count on rerunning the prompt to get them back.",
   "Tune temperature for variety, not accuracy: a low setting can repeat a wrong answer.",
   "Spend reasoning on math, code and planning; for missing facts, add sources, not thinking."
  ],
  "red_flags": [
   "The only verification step is asking the model to double-check itself",
   "Citations, IDs or amounts in the output with no lookup behind them",
   "Quality judged from one good demo run, with no repeats and no test set",
   "“A human reviews it” with no time, tooling or sample rate to make it real"
  ],
  "terms": [
   {
    "term": "Token probability",
    "def": "The score the model gives each possible next token before one is picked."
   },
   {
    "term": "Temperature",
    "def": "A setting that sharpens or flattens those odds before a token is sampled."
   },
   {
    "term": "Hallucination",
    "def": "Fluent output that isn’t supported by facts or by the sources provided."
   },
   {
    "term": "Test-time compute",
    "def": "Extra tokens spent reasoning at answer time: better odds, more cost and latency."
   },
   {
    "term": "Deterministic check",
    "def": "A check in code, data or rules that doesn’t depend on the model’s own guess."
   }
  ],
  "tool": {
   "title": "Probabilistic or verified?",
   "kind": "decision",
   "items": [
    "If variety is the point (names, drafts, ideas) → leave it probabilistic; test with real users",
    "If a person reads it next to the source → probabilistic is OK; show or link the source",
    "If code consumes it → validate the schema and the values; reject, retry or fall back",
    "If it states a number, price, date or citation → fetch it from a source system; don’t generate it",
    "If it triggers an action or moves money → code computes and permits it; a person approves risky ones",
    "If an error can’t be caught or undone → don’t automate it; keep a person deciding"
   ]
  }
 },
 "m04": {
  "big_idea": "Treat the context like an API contract: every part needs an owner and a trust level.",
  "ask": [
   "What exactly does the model receive on one request, in order? Can we log it?",
   "Who owns each part of the context, and when was it last reviewed?",
   "Which parts can a user, an email, a web page or a tool result write into?",
   "If injected text took control, what is the worst the system would let it do?",
   "What gets trimmed, summarized or dropped when the window fills up?"
  ],
  "rules": [
   "Fix a conflicting instruction at its source; never add a rule to overrule another.",
   "Label untrusted content with its source and pass it as data, never as instructions.",
   "Vary few-shot examples and include an edge case; the model copies their flaws too.",
   "Cap what a hijacked model can do: least-privilege tools, approval for sends and deletes."
  ],
  "red_flags": [
   "Nobody can say who owns the system prompt",
   "The prompt grows by one rule per incident and nothing is ever removed",
   "Retrieved text or tool output pasted in raw, with no labels or delimiters",
   "One flow mixes private data, untrusted content and a way to send data out"
  ],
  "terms": [
   {
    "term": "Context window",
    "def": "Everything the model receives on one call: rules, examples, history, data, task."
   },
   {
    "term": "System instructions",
    "def": "Your team’s role, rules and format, re-sent every call; weighted higher, not enforced."
   },
   {
    "term": "Few-shot examples",
    "def": "Sample inputs and outputs in the context that the model copies closely."
   },
   {
    "term": "Context pollution",
    "def": "Stale, conflicting or irrelevant text that distracts or misleads the model."
   },
   {
    "term": "Indirect injection",
    "def": "Instructions hidden in content the model reads, like an email, page or tool result."
   }
  ],
  "tool": {
   "title": "Context assembly template",
   "kind": "template",
   "items": [
    "Role and rules: purpose, hard limits and tone; one owner, no conflicts, stable so it caches",
    "Examples: a few varied input and output pairs in the target format, including an edge case",
    "Reference material: only relevant chunks, delimited, labeled with source and date, as data",
    "Tool results: the fields the task needs, not raw dumps, labeled with the system they came from",
    "History: recent turns that still matter; older ones summarized or dropped",
    "Task and output format: the current question restated, plus the schema or format required"
   ]
  }
 },
 "m05": {
  "big_idea": "Before choosing a mechanism, ask: is this information, state or behavior?",
  "ask": [
   "Is this information to know, state to track, or behavior to shape?",
   "How often does this knowledge change, and who updates the source?",
   "Must the answer be exact and live, or is the closest match good enough?",
   "Who may see each document or memory, and is that filtered before retrieval?",
   "When an answer is wrong, can we see which chunks were retrieved?"
  ],
  "rules": [
   "Retrieve facts that change or need a citation; don’t bake them into the weights.",
   "Read orders, balances and permissions from the database of record, never from memory.",
   "Combine meaning-based and keyword search when users look up codes, names or IDs.",
   "Fine-tune only after prompting falls short and you have labeled examples and an eval set."
  ],
  "red_flags": [
   "Fine-tuning proposed to teach the model the company’s documents",
   "A wrong answer blamed on the model before anyone checked what was retrieved",
   "Access permissions applied after retrieval, or not at all",
   "Stored memory that users can’t see, correct or delete"
  ],
  "terms": [
   {
    "term": "Embedding",
    "def": "A list of numbers representing text, so similar meanings sit close together."
   },
   {
    "term": "Chunking",
    "def": "Splitting documents into passages that can be found and read on their own."
   },
   {
    "term": "RAG",
    "def": "Retrieval-augmented generation: search first, then answer from what was found."
   },
   {
    "term": "Application memory",
    "def": "State the system stores and re-sends, like preferences or summaries of past chats."
   },
   {
    "term": "Fine-tuning",
    "def": "Further training on your examples; it changes the weights, and so the behavior."
   }
  ],
  "tool": {
   "title": "Pick the mechanism",
   "kind": "decision",
   "items": [
    "If it’s a stable rule, tone or short style guide → prompt, with good and bad examples",
    "If it’s documents that change or need sources → retrieval with citations and metadata filters",
    "If it’s per-user preferences or context across sessions → application memory the user can see",
    "If it must be exact and live (orders, balances, permissions) → database, via code or a tool",
    "If prompts can’t hold a format or narrow task at your volume and cost → fine-tune, with evals",
    "If it spans several → combine them, but name the primary mechanism and who owns it"
   ]
  }
 },
 "m06": {
  "big_idea": "The model only asks. Your code decides what runs, and with whose rights.",
  "ask": [
   "What is the worst thing each tool can do if the model calls it wrongly?",
   "Whose credentials does each tool run with: the user’s, or a service account?",
   "Which actions can’t be undone, and where does the user confirm them?",
   "What happens if the same tool call is retried or sent twice?",
   "Which tool results carry untrusted text, such as web pages, emails or documents?"
  ],
  "rules": [
   "Give each tool one narrow job; never expose raw SQL, HTTP or shell to the model.",
   "Enforce limits in code; a rule that lives only in the prompt is not a control.",
   "Require confirmation in the interface for anything that spends, sends or deletes.",
   "Run every tool with the signed-in user’s permissions, never an admin account."
  ],
  "red_flags": [
   "One tool like run_sql or call_api that can do almost anything",
   "“We told the model not to” offered as the safety plan",
   "API keys, tokens or card numbers appear in prompts or tool arguments",
   "Nobody can say which tool calls ran yesterday, with which arguments"
  ],
  "terms": [
   {
    "term": "Tool call",
    "def": "A structured request from the model: a tool name plus arguments your app may run."
   },
   {
    "term": "Least privilege",
    "def": "Give each tool only the access its task needs, and nothing more."
   },
   {
    "term": "Idempotency key",
    "def": "An ID sent with a request so a retry doesn’t repeat the action, like a double booking."
   },
   {
    "term": "Prompt injection",
    "def": "Text in inputs or tool results written to steer the model against your instructions."
   },
   {
    "term": "MCP server",
    "def": "A program that exposes tools and data to apps through a shared, open protocol."
   }
  ],
  "tool": {
   "title": "Tool design review",
   "kind": "checklist",
   "items": [
    "One narrow job, with a name and description clear enough for the model to choose it correctly",
    "Risk level set: read, reversible write, irreversible, or never exposed to the model",
    "Arguments typed and validated in code: types, enums, ranges, and that IDs belong to the user",
    "Irreversible or costly actions need user confirmation in the interface, not in chat text",
    "Runs with the user’s scoped permissions; credentials stay in the app, never in context",
    "Every call logged with arguments and result; retries carry an idempotency key"
   ]
  }
 },
 "m07": {
  "big_idea": "Autonomy is a cost: give the model a decision only where code can’t cover the cases.",
  "ask": [
   "Who decides the next step here: our code, or the model?",
   "Are the steps the same for every input, or do they depend on what it finds?",
   "What stops the loop: a step limit, a budget, a timeout or a human?",
   "If step 3 is wrong, which later step or person notices it, and when?",
   "If a run fails halfway, what state do we need to resume it or undo it?"
  ],
  "rules": [
   "Make known steps fixed code; keep model decisions for the parts that truly vary.",
   "Set step, budget and time limits in code, and decide what happens when one is hit.",
   "Check key results before they enter state; later steps will treat them as facts.",
   "Put approval on few, high-risk actions, and show the approver the evidence."
  ],
  "red_flags": [
   "It’s called an agent, but nobody can say what the model decides",
   "No step limit or budget, so a stuck run keeps retrying the same action",
   "One person approves hundreds of actions a day without reading them",
   "More agents are added before a simple workflow was tried and measured"
  ],
  "terms": [
   {
    "term": "Workflow",
    "def": "Code fixes the order of steps; the model only fills in some of them."
   },
   {
    "term": "Agent loop",
    "def": "The model picks the next action, the system runs it, and the result feeds the next turn."
   },
   {
    "term": "Router",
    "def": "One model decision that sends an input down one of several fixed paths."
   },
   {
    "term": "State",
    "def": "What a run carries forward: goal, history, notes and changes made in other systems."
   },
   {
    "term": "Blast radius",
    "def": "How much damage one wrong action can do before anyone can stop or undo it."
   }
  ],
  "tool": {
   "title": "How much autonomy?",
   "kind": "decision",
   "items": [
    "If the steps are the same for every input → fixed workflow; the model only fills in steps",
    "If inputs fall into a few known paths → router: one model decision, then fixed code",
    "If the path depends on what it finds and tools are read-only → bounded agent with caps",
    "If an action sends, spends, deletes or changes production → a human approves it first",
    "If an action can’t be undone and approval isn’t practical → don’t expose it as a tool",
    "If you can’t yet measure whole runs → stay one level less autonomous until you can"
   ]
  }
 },
 "m08": {
  "big_idea": "If you can’t name the number that would make you roll back, you don’t know it works.",
  "ask": [
   "Which written cases define “working” for this feature, and who agreed on them?",
   "Which quality checks can plain code do before we reach for a model judge?",
   "Which failure type is most common, and what does each type cost us?",
   "What reruns the set when a prompt, model, index or tool changes?",
   "What p95 latency and cost per request can this use case afford?"
  ],
  "rules": [
   "Grade with code first, a calibrated judge next, and people to set the rubric.",
   "Turn every production failure into a golden-set case before you fix it.",
   "Compare pass rates over repeated runs, not single outputs, before judging a change.",
   "Block a release when golden-set scores drop below the stored baseline."
  ],
  "red_flags": [
   "Quality is shown only with hand-picked demo examples",
   "A single accuracy number with no breakdown by failure type",
   "A model judge in use with no check against human labels",
   "The app calls an unpinned model name and nothing reruns the set"
  ],
  "terms": [
   {
    "term": "Golden set",
    "def": "A small, curated, versioned set of real cases the team agrees defines “working”."
   },
   {
    "term": "Grader",
    "def": "Anything that scores an output: a code check, a human rater or a model judge."
   },
   {
    "term": "LLM-as-a-judge",
    "def": "A model that grades outputs against a written rubric; calibrate it against people."
   },
   {
    "term": "Regression test",
    "def": "Rerunning the set after a change to catch cases that used to pass and now fail."
   },
   {
    "term": "p95 latency",
    "def": "The response time 95% of requests beat; it shows what the slow cases feel like."
   }
  ],
  "tool": {
   "title": "One-page evaluation plan",
   "kind": "template",
   "items": [
    "Scope: the feature, its users, and what a costly error looks like",
    "Golden set: sources (logs, tickets, past failures), size, hard cases, who maintains it",
    "Graders: one per criterion (code check, calibrated judge or human), with the rubric",
    "Pass thresholds: per criterion and per failure type, plus the baseline to compare against",
    "Regression trigger: which changes rerun the set, and what score drop blocks a release",
    "Budgets and owner: cost per request, p95 latency, and who acts when a number slips"
   ]
  }
 }
};
